# .github/stale.yml

# Сколько дней ждать без активности, прежде чем пометить как stale
daysUntilStale: 2

# Сколько дней после пометки 'stale' ждать до закрытия
daysUntilClose: 0

# Сообщение, которое будет оставлено при пометке как stale
staleIssueMessage: >
  ⚠️ Этот issue неактивен уже 7 дней. Он будет закрыт автоматически.

# Сообщение при закрытии issue
closeIssueMessage: >
  🔒 Этот issue был автоматически закрыт из-за отсутствия активности.

# Название метки, которая будет ставиться
staleLabel: stale

# Исключить некоторые метки (например, 'pinned' или 'keep-open')
exemptLabels:
  - pinned
  - keep-open

# Настройки для Pull Requests (если не используешь — оставь пустыми)
daysUntilStaleForPR: 60
daysUntilCloseForPR: 7
stalePrMessage: >
  Этот Pull Request неактивен. Он будет закрыт, если не будет обновлён.
closePrMessage: >
  Этот Pull Request был автоматически закрыт.

# Не трогать заархивированные репозитории
exemptArchived: true
