name: "Stale Bot"

on:
  schedule:
    - cron: "0 0 * * *"  # Каждый день в 00:00 UTC
  workflow_dispatch:      # Возможность ручного запуска

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: ${{ vars.staleIssueMessage }}
          close-issue-message: ${{ vars.closeIssueMessage }}
          stale-pr-message: ${{ vars.stalePrMessage }}
          close-pr-message: ${{ vars.closePrMessage }}
